set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property -dict {PACKAGE_PIN V5  IOSTANDARD LVCMOS33} [get_ports mlvds_de[0]]
set_property -dict {PACKAGE_PIN U10 IOSTANDARD LVCMOS33} [get_ports mlvds_re[0]]
set_property -dict {PACKAGE_PIN V7  IOSTANDARD LVCMOS33} [get_ports mlvds_tx[0]]
set_property -dict {PACKAGE_PIN U7  IOSTANDARD LVCMOS33 PULLDOWN true} [get_ports mlvds_rx[0]]

set_property -dict {PACKAGE_PIN Y6  IOSTANDARD LVCMOS33} [get_ports mlvds_de[1]]
set_property -dict {PACKAGE_PIN V8  IOSTANDARD LVCMOS33} [get_ports mlvds_re[1]]
set_property -dict {PACKAGE_PIN Y8  IOSTANDARD LVCMOS33} [get_ports mlvds_tx[1]]
set_property -dict {PACKAGE_PIN Y9  IOSTANDARD LVCMOS33 PULLDOWN true} [get_ports mlvds_rx[1]]

set_property -dict {PACKAGE_PIN T9  IOSTANDARD LVCMOS33} [get_ports mlvds_clk]


set_property -dict {PACKAGE_PIN U9   IOSTANDARD LVCMOS33} [get_ports rs422_tx[0]]
set_property -dict {PACKAGE_PIN U8   IOSTANDARD LVCMOS33} [get_ports rs422_rx[0]]
set_property -dict {PACKAGE_PIN W11  IOSTANDARD LVCMOS33} [get_ports rs422_tx[1]]
set_property -dict {PACKAGE_PIN Y11  IOSTANDARD LVCMOS33} [get_ports rs422_rx[1]]
set_property -dict {PACKAGE_PIN T5   IOSTANDARD LVCMOS33} [get_ports rs422_tx[2]]
set_property -dict {PACKAGE_PIN U5   IOSTANDARD LVCMOS33} [get_ports rs422_rx[2]]
#set_property -dict {PACKAGE_PIN T5   IOSTANDARD LVCMOS33} [get_ports rs422_tx[3]]
#set_property -dict {PACKAGE_PIN U5   IOSTANDARD LVCMOS33} [get_ports rs422_rx[3]]
set_property -dict {PACKAGE_PIN V6   IOSTANDARD LVCMOS33} [get_ports rs232_dbg_tx]
set_property -dict {PACKAGE_PIN V10  IOSTANDARD LVCMOS33} [get_ports rs232_dbg_rx]

#set_property -dict {PACKAGE_PIN Y7 IOSTANDARD LVCMOS33} [get_ports pl_clk]
set_property -dict {PACKAGE_PIN H17 IOSTANDARD LVCMOS33} [get_ports ema_clk_p]
#set_property -dict {PACKAGE_PIN Y12 IOSTANDARD LVCMOS33} [get_ports rst_n]
set_property -dict {PACKAGE_PIN G14 IOSTANDARD LVCMOS33} [get_ports {ema_a[0]}]
set_property -dict {PACKAGE_PIN C20 IOSTANDARD LVCMOS33} [get_ports {ema_a[1]}]
set_property -dict {PACKAGE_PIN B20 IOSTANDARD LVCMOS33} [get_ports {ema_a[2]}]
set_property -dict {PACKAGE_PIN B19 IOSTANDARD LVCMOS33} [get_ports {ema_a[3]}]
set_property -dict {PACKAGE_PIN A20 IOSTANDARD LVCMOS33} [get_ports {ema_a[4]}]
set_property -dict {PACKAGE_PIN E17 IOSTANDARD LVCMOS33} [get_ports {ema_a[5]}]
set_property -dict {PACKAGE_PIN D18 IOSTANDARD LVCMOS33} [get_ports {ema_a[6]}]
set_property -dict {PACKAGE_PIN D19 IOSTANDARD LVCMOS33} [get_ports {ema_a[7]}]
set_property -dict {PACKAGE_PIN D20 IOSTANDARD LVCMOS33} [get_ports {ema_a[8]}]
set_property -dict {PACKAGE_PIN E18 IOSTANDARD LVCMOS33} [get_ports {ema_a[9]}]
set_property -dict {PACKAGE_PIN E19 IOSTANDARD LVCMOS33} [get_ports {ema_a[10]}]
set_property -dict {PACKAGE_PIN F16 IOSTANDARD LVCMOS33} [get_ports {ema_a[11]}]
set_property -dict {PACKAGE_PIN F17 IOSTANDARD LVCMOS33} [get_ports {ema_a[12]}]
set_property -dict {PACKAGE_PIN M19 IOSTANDARD LVCMOS33} [get_ports {ema_a[13]}]
set_property -dict {PACKAGE_PIN M20 IOSTANDARD LVCMOS33} [get_ports {ema_a[14]}]
set_property -dict {PACKAGE_PIN M17 IOSTANDARD LVCMOS33} [get_ports {ema_a[15]}]
#set_property -dict {PACKAGE_PIN M18 IOSTANDARD LVCMOS33} [get_ports {ema_ba[0]}]
#set_property -dict {PACKAGE_PIN L19 IOSTANDARD LVCMOS33} [get_ports {ema_ba[1]}]
#set_property -dict {PACKAGE_PIN M14 IOSTANDARD LVCMOS33} [get_ports {ema_wen_dqm[1]}]
#set_property -dict {PACKAGE_PIN M15 IOSTANDARD LVCMOS33} [get_ports {ema_wen_dqm[0]}]
set_property -dict {PACKAGE_PIN L20 IOSTANDARD LVCMOS33} [get_ports {ema_d[0]}]
set_property -dict {PACKAGE_PIN K19 IOSTANDARD LVCMOS33} [get_ports {ema_d[1]}]
set_property -dict {PACKAGE_PIN J19 IOSTANDARD LVCMOS33} [get_ports {ema_d[2]}]
set_property -dict {PACKAGE_PIN L16 IOSTANDARD LVCMOS33} [get_ports {ema_d[3]}]
set_property -dict {PACKAGE_PIN L17 IOSTANDARD LVCMOS33} [get_ports {ema_d[4]}]
set_property -dict {PACKAGE_PIN K17 IOSTANDARD LVCMOS33} [get_ports {ema_d[5]}]
set_property -dict {PACKAGE_PIN K18 IOSTANDARD LVCMOS33} [get_ports {ema_d[6]}]
set_property -dict {PACKAGE_PIN H16 IOSTANDARD LVCMOS33} [get_ports {ema_d[7]}]
set_property -dict {PACKAGE_PIN H18 IOSTANDARD LVCMOS33} [get_ports {ema_d[8]}]
set_property -dict {PACKAGE_PIN F19 IOSTANDARD LVCMOS33} [get_ports {ema_d[9]}]
set_property -dict {PACKAGE_PIN F20 IOSTANDARD LVCMOS33} [get_ports {ema_d[10]}]
set_property -dict {PACKAGE_PIN G17 IOSTANDARD LVCMOS33} [get_ports {ema_d[11]}]
set_property -dict {PACKAGE_PIN G18 IOSTANDARD LVCMOS33} [get_ports {ema_d[12]}]
set_property -dict {PACKAGE_PIN J20 IOSTANDARD LVCMOS33} [get_ports {ema_d[13]}]
set_property -dict {PACKAGE_PIN H20 IOSTANDARD LVCMOS33} [get_ports {ema_d[14]}]
set_property -dict {PACKAGE_PIN G19 IOSTANDARD LVCMOS33} [get_ports {ema_d[15]}]
set_property -dict {PACKAGE_PIN J14 IOSTANDARD LVCMOS33} [get_ports ema_wen]
set_property -dict {PACKAGE_PIN N15 IOSTANDARD LVCMOS33} [get_ports ema_oen]
#set_property -dict {PACKAGE_PIN N16 IOSTANDARD LVCMOS33} [get_ports ema_a_rwn]
set_property -dict {PACKAGE_PIN H15 IOSTANDARD LVCMOS33} [get_ports {ema_csn[2]}]
set_property -dict {PACKAGE_PIN K14 IOSTANDARD LVCMOS33} [get_ports {ema_csn[4]}]
set_property -dict {PACKAGE_PIN J15 IOSTANDARD LVCMOS33} [get_ports {ema_csn[5]}]

#set_property -dict {PACKAGE_PIN V5 IOSTANDARD LVCMOS33} [get_ports mlvds_de]
#set_property -dict {PACKAGE_PIN U10 IOSTANDARD LVCMOS33} [get_ports mlvds_re]
#set_property -dict {PACKAGE_PIN V7 IOSTANDARD LVCMOS33} [get_ports mlvds_tx]
#set_property -dict {PACKAGE_PIN U7 IOSTANDARD LVCMOS33} [get_ports mlvds_rx]

set_property -dict {PACKAGE_PIN V18 IOSTANDARD LVCMOS33} [get_ports {dsp_io[0]}]




