# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/PROJECT/mibus/nanli_gfk8736_he/zynq_sys.srcs/sources_1/ip/ila_uart/ila_uart.xci
# IP: The module: 'ila_uart' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/PROJECT/mibus/nanli_gfk8736_he/zynq_sys.srcs/sources_1/ip/ila_uart/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_uart'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/PROJECT/mibus/nanli_gfk8736_he/zynq_sys.srcs/sources_1/ip/ila_uart/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_uart'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/PROJECT/mibus/nanli_gfk8736_he/zynq_sys.srcs/sources_1/ip/ila_uart/ila_uart_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_uart'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: E:/PROJECT/mibus/nanli_gfk8736_he/zynq_sys.srcs/sources_1/ip/ila_uart/ila_uart.xci
# IP: The module: 'ila_uart' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/PROJECT/mibus/nanli_gfk8736_he/zynq_sys.srcs/sources_1/ip/ila_uart/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_uart'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/PROJECT/mibus/nanli_gfk8736_he/zynq_sys.srcs/sources_1/ip/ila_uart/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_uart'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/PROJECT/mibus/nanli_gfk8736_he/zynq_sys.srcs/sources_1/ip/ila_uart/ila_uart_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_uart'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
