# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/system.xdc

# XDC: new/time.xdc

# Block Designs: bd/system_bd/system_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_bd || ORIG_REF_NAME==system_bd} -quiet] -quiet

# IP: bd/system_bd/ip/system_bd_processing_system7_0_0/system_bd_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_bd_processing_system7_0_0 || ORIG_REF_NAME==system_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/system_bd/ip/system_bd_axi_protocol_convert_0_0/system_bd_axi_protocol_convert_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_bd_axi_protocol_convert_0_0 || ORIG_REF_NAME==system_bd_axi_protocol_convert_0_0} -quiet] -quiet

# IP: bd/system_bd/ip/system_bd_axi_emif_0_0/system_bd_axi_emif_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_bd_axi_emif_0_0 || ORIG_REF_NAME==system_bd_axi_emif_0_0} -quiet] -quiet

# IP: bd/system_bd/ip/system_bd_ps7_0_axi_periph_0/system_bd_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_bd_ps7_0_axi_periph_0 || ORIG_REF_NAME==system_bd_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/system_bd/ip/system_bd_rst_ps7_0_100M_0/system_bd_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_bd_rst_ps7_0_100M_0 || ORIG_REF_NAME==system_bd_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/system_bd/ip/system_bd_auto_pc_0/system_bd_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_bd_auto_pc_0 || ORIG_REF_NAME==system_bd_auto_pc_0} -quiet] -quiet

# XDC: bd/system_bd/system_bd_ooc.xdc
