# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg400-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/PROJECT/mibus/ninli_fk/nanli_gfk8736_test/zynq_sys.cache/wt [current_project]
set_property parent.project_path E:/PROJECT/mibus/ninli_fk/nanli_gfk8736_test/zynq_sys.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths e:/PROJECT/ip_repo [current_project]
update_ip_catalog
set_property ip_output_repo e:/PROJECT/mibus/ninli_fk/nanli_gfk8736_test/zynq_sys.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet E:/PROJECT/mibus/ninli_fk/nanli_gfk8736_test/zynq_sys.srcs/sources_1/axi_lite_to_apb_muti.dcp
set_property used_in_implementation false [get_files E:/PROJECT/mibus/ninli_fk/nanli_gfk8736_test/zynq_sys.srcs/sources_1/axi_lite_to_apb_muti.dcp]
read_verilog -library xil_defaultlib {
  E:/PROJECT/mibus/ninli_fk/nanli_gfk8736_test/zynq_sys.srcs/sources_1/apb_uart.v
  E:/PROJECT/mibus/ninli_fk/nanli_gfk8736_test/zynq_sys.srcs/sources_1/axi_lite_to_drp_wrapper.v
  E:/PROJECT/mibus/ninli_fk/nanli_gfk8736_test/zynq_sys.srcs/sources_1/axis_d16_w8_to_r8.v
  E:/PROJECT/mibus/ninli_fk/nanli_gfk8736_test/zynq_sys.srcs/sources_1/mlvds_arbter.v
  E:/PROJECT/mibus/ninli_fk/nanli_gfk8736_test/zynq_sys.srcs/sources_1/mlvds_top.v
  E:/PROJECT/mibus/ninli_fk/nanli_gfk8736_test/zynq_sys.srcs/sources_1/mlvds_wrapper.v
  E:/PROJECT/mibus/ninli_fk/nanli_gfk8736_test/zynq_sys.srcs/sources_1/rs422_wrapper.v
  E:/PROJECT/mibus/ninli_fk/nanli_gfk8736_test/zynq_sys.srcs/sources_1/top.v
}
add_files E:/PROJECT/mibus/ninli_fk/nanli_gfk8736_test/zynq_sys.srcs/sources_1/bd/system_bd/system_bd.bd
set_property used_in_implementation false [get_files -all e:/PROJECT/mibus/ninli_fk/nanli_gfk8736_test/zynq_sys.srcs/sources_1/bd/system_bd/ip/system_bd_processing_system7_0_0/system_bd_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/PROJECT/mibus/ninli_fk/nanli_gfk8736_test/zynq_sys.srcs/sources_1/bd/system_bd/ip/system_bd_axi_protocol_convert_0_0/system_bd_axi_protocol_convert_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/PROJECT/mibus/ninli_fk/nanli_gfk8736_test/zynq_sys.srcs/sources_1/bd/system_bd/ip/system_bd_axi_emif_0_0/src/fifo_dsp_zynq/fifo_dsp_zynq.xdc]
set_property used_in_implementation false [get_files -all e:/PROJECT/mibus/ninli_fk/nanli_gfk8736_test/zynq_sys.srcs/sources_1/bd/system_bd/ip/system_bd_axi_emif_0_0/src/fifo_dsp_zynq/fifo_dsp_zynq_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/PROJECT/mibus/ninli_fk/nanli_gfk8736_test/zynq_sys.srcs/sources_1/bd/system_bd/ip/system_bd_axi_emif_0_0/src/fifo_zynq_dsp/fifo_zynq_dsp.xdc]
set_property used_in_implementation false [get_files -all e:/PROJECT/mibus/ninli_fk/nanli_gfk8736_test/zynq_sys.srcs/sources_1/bd/system_bd/ip/system_bd_axi_emif_0_0/src/fifo_zynq_dsp/fifo_zynq_dsp_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/PROJECT/mibus/ninli_fk/nanli_gfk8736_test/zynq_sys.srcs/sources_1/bd/system_bd/ip/system_bd_rst_ps7_0_100M_0/system_bd_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/PROJECT/mibus/ninli_fk/nanli_gfk8736_test/zynq_sys.srcs/sources_1/bd/system_bd/ip/system_bd_rst_ps7_0_100M_0/system_bd_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all e:/PROJECT/mibus/ninli_fk/nanli_gfk8736_test/zynq_sys.srcs/sources_1/bd/system_bd/ip/system_bd_rst_ps7_0_100M_0/system_bd_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/PROJECT/mibus/ninli_fk/nanli_gfk8736_test/zynq_sys.srcs/sources_1/bd/system_bd/ip/system_bd_auto_pc_0/system_bd_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all E:/PROJECT/mibus/ninli_fk/nanli_gfk8736_test/zynq_sys.srcs/sources_1/bd/system_bd/system_bd_ooc.xdc]

read_ip -quiet E:/PROJECT/mibus/ninli_fk/nanli_gfk8736_test/zynq_sys.srcs/sources_1/ip/ila_uart/ila_uart.xci
set_property used_in_synthesis false [get_files -all e:/PROJECT/mibus/ninli_fk/nanli_gfk8736_test/zynq_sys.srcs/sources_1/ip/ila_uart/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/PROJECT/mibus/ninli_fk/nanli_gfk8736_test/zynq_sys.srcs/sources_1/ip/ila_uart/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/PROJECT/mibus/ninli_fk/nanli_gfk8736_test/zynq_sys.srcs/sources_1/ip/ila_uart/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all e:/PROJECT/mibus/ninli_fk/nanli_gfk8736_test/zynq_sys.srcs/sources_1/ip/ila_uart/ila_uart_ooc.xdc]

read_ip -quiet E:/PROJECT/mibus/ninli_fk/nanli_gfk8736_test/zynq_sys.srcs/sources_1/ip/sfifo_d2k_w9_to_r9/sfifo_d2k_w9_to_r9.xci
set_property used_in_implementation false [get_files -all e:/PROJECT/mibus/ninli_fk/nanli_gfk8736_test/zynq_sys.srcs/sources_1/ip/sfifo_d2k_w9_to_r9/sfifo_d2k_w9_to_r9.xdc]
set_property used_in_implementation false [get_files -all e:/PROJECT/mibus/ninli_fk/nanli_gfk8736_test/zynq_sys.srcs/sources_1/ip/sfifo_d2k_w9_to_r9/sfifo_d2k_w9_to_r9_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/PROJECT/mibus/ninli_fk/nanli_gfk8736_test/zynq_sys.srcs/constrs_1/new/system.xdc
set_property used_in_implementation false [get_files E:/PROJECT/mibus/ninli_fk/nanli_gfk8736_test/zynq_sys.srcs/constrs_1/new/system.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7z020clg400-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
