# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/PROJECT/mibus/nanli_gfk8736_he/zynq_sys.srcs/sources_1/ip/sfifo_d2k_w9_to_r9/sfifo_d2k_w9_to_r9.xci
# IP: The module: 'sfifo_d2k_w9_to_r9' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/PROJECT/mibus/nanli_gfk8736_he/zynq_sys.srcs/sources_1/ip/sfifo_d2k_w9_to_r9/sfifo_d2k_w9_to_r9.xdc
# XDC: The top module name and the constraint reference have the same name: 'sfifo_d2k_w9_to_r9'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/PROJECT/mibus/nanli_gfk8736_he/zynq_sys.srcs/sources_1/ip/sfifo_d2k_w9_to_r9/sfifo_d2k_w9_to_r9_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sfifo_d2k_w9_to_r9'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/PROJECT/mibus/nanli_gfk8736_he/zynq_sys.srcs/sources_1/ip/sfifo_d2k_w9_to_r9/sfifo_d2k_w9_to_r9.xci
# IP: The module: 'sfifo_d2k_w9_to_r9' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/PROJECT/mibus/nanli_gfk8736_he/zynq_sys.srcs/sources_1/ip/sfifo_d2k_w9_to_r9/sfifo_d2k_w9_to_r9.xdc
# XDC: The top module name and the constraint reference have the same name: 'sfifo_d2k_w9_to_r9'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/PROJECT/mibus/nanli_gfk8736_he/zynq_sys.srcs/sources_1/ip/sfifo_d2k_w9_to_r9/sfifo_d2k_w9_to_r9_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sfifo_d2k_w9_to_r9'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
